#!/bin/zsh
export EDITOR=vim
export VISUAL=$EDITOR

export HISTFILE

[ -f $HOME/.zsh.d/sshagent ] && . $HOME/.zsh.d/sshagent

if [ -d $HOME/.zsh.d/completion ];then
    fpath=($HOME/.zsh.d/completion $fpath)
    autoload -U compinit
    compinit
fi
