#!/usr/bin/env zsh

if ! [ -z "$ANDROID_HOME" ];then
  ANDROID_BUILD_TOOLS_VERSION=19.0.0

  PATH=$ANDROID_HOME/tools:$PATH
  PATH=$ANDROID_HOME/platform-tools:$PATH
  PATH=$ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION:$PATH
fi

export PATH=/opt/local/bin:/opt/local/sbin:$PATH
